config setup
    charondebug="ike 1, knl 1, cfg 0"
    uniqueids=yes

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    authby=secret
    keyexchange=ikev2

conn branchB-to-branchA
    left=10.0.0.20
    leftsubnet=10.0.0.20/32
    right=10.0.0.10
    rightsubnet=10.0.0.10/32
    auto=start
    type=tunnel
